// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Runtime/GrpcInterface/platform.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Mpf.Vpe {
  public static partial class MpfHardwareService
  {
    static readonly string __ServiceName = "mpf.vpe.MpfHardwareService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Mpf.Vpe.MachineState> __Marshaller_mpf_vpe_MachineState = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Mpf.Vpe.MachineState.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Mpf.Vpe.Commands> __Marshaller_mpf_vpe_Commands = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Mpf.Vpe.Commands.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Mpf.Vpe.EmptyRequest> __Marshaller_mpf_vpe_EmptyRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Mpf.Vpe.EmptyRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Mpf.Vpe.MachineDescription> __Marshaller_mpf_vpe_MachineDescription = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Mpf.Vpe.MachineDescription.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Mpf.Vpe.SwitchChanges> __Marshaller_mpf_vpe_SwitchChanges = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Mpf.Vpe.SwitchChanges.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Mpf.Vpe.EmptyResponse> __Marshaller_mpf_vpe_EmptyResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Mpf.Vpe.EmptyResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Mpf.Vpe.QuitRequest> __Marshaller_mpf_vpe_QuitRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Mpf.Vpe.QuitRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Mpf.Vpe.PingResponse> __Marshaller_mpf_vpe_PingResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Mpf.Vpe.PingResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Mpf.Vpe.MachineState, global::Mpf.Vpe.Commands> __Method_Start = new grpc::Method<global::Mpf.Vpe.MachineState, global::Mpf.Vpe.Commands>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "Start",
        __Marshaller_mpf_vpe_MachineState,
        __Marshaller_mpf_vpe_Commands);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Mpf.Vpe.EmptyRequest, global::Mpf.Vpe.MachineDescription> __Method_GetMachineDescription = new grpc::Method<global::Mpf.Vpe.EmptyRequest, global::Mpf.Vpe.MachineDescription>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetMachineDescription",
        __Marshaller_mpf_vpe_EmptyRequest,
        __Marshaller_mpf_vpe_MachineDescription);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Mpf.Vpe.SwitchChanges, global::Mpf.Vpe.EmptyResponse> __Method_SendSwitchChanges = new grpc::Method<global::Mpf.Vpe.SwitchChanges, global::Mpf.Vpe.EmptyResponse>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "SendSwitchChanges",
        __Marshaller_mpf_vpe_SwitchChanges,
        __Marshaller_mpf_vpe_EmptyResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Mpf.Vpe.QuitRequest, global::Mpf.Vpe.EmptyResponse> __Method_Quit = new grpc::Method<global::Mpf.Vpe.QuitRequest, global::Mpf.Vpe.EmptyResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Quit",
        __Marshaller_mpf_vpe_QuitRequest,
        __Marshaller_mpf_vpe_EmptyResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Mpf.Vpe.EmptyRequest, global::Mpf.Vpe.PingResponse> __Method_Ping = new grpc::Method<global::Mpf.Vpe.EmptyRequest, global::Mpf.Vpe.PingResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Ping",
        __Marshaller_mpf_vpe_EmptyRequest,
        __Marshaller_mpf_vpe_PingResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Mpf.Vpe.PlatformReflection.Descriptor.Services[0]; }
    }

    /// <summary>Client for MpfHardwareService</summary>
    public partial class MpfHardwareServiceClient : grpc::ClientBase<MpfHardwareServiceClient>
    {
      /// <summary>Creates a new client for MpfHardwareService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public MpfHardwareServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for MpfHardwareService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public MpfHardwareServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected MpfHardwareServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected MpfHardwareServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Mpf.Vpe.Commands> Start(global::Mpf.Vpe.MachineState request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Start(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Mpf.Vpe.Commands> Start(global::Mpf.Vpe.MachineState request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_Start, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Mpf.Vpe.MachineDescription GetMachineDescription(global::Mpf.Vpe.EmptyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetMachineDescription(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Mpf.Vpe.MachineDescription GetMachineDescription(global::Mpf.Vpe.EmptyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetMachineDescription, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Mpf.Vpe.MachineDescription> GetMachineDescriptionAsync(global::Mpf.Vpe.EmptyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetMachineDescriptionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Mpf.Vpe.MachineDescription> GetMachineDescriptionAsync(global::Mpf.Vpe.EmptyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetMachineDescription, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::Mpf.Vpe.SwitchChanges, global::Mpf.Vpe.EmptyResponse> SendSwitchChanges(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SendSwitchChanges(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncClientStreamingCall<global::Mpf.Vpe.SwitchChanges, global::Mpf.Vpe.EmptyResponse> SendSwitchChanges(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_SendSwitchChanges, null, options);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Mpf.Vpe.EmptyResponse Quit(global::Mpf.Vpe.QuitRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Quit(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Mpf.Vpe.EmptyResponse Quit(global::Mpf.Vpe.QuitRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Quit, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Mpf.Vpe.EmptyResponse> QuitAsync(global::Mpf.Vpe.QuitRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return QuitAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Mpf.Vpe.EmptyResponse> QuitAsync(global::Mpf.Vpe.QuitRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Quit, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Mpf.Vpe.PingResponse Ping(global::Mpf.Vpe.EmptyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Ping(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Mpf.Vpe.PingResponse Ping(global::Mpf.Vpe.EmptyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Ping, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Mpf.Vpe.PingResponse> PingAsync(global::Mpf.Vpe.EmptyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PingAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Mpf.Vpe.PingResponse> PingAsync(global::Mpf.Vpe.EmptyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Ping, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override MpfHardwareServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new MpfHardwareServiceClient(configuration);
      }
    }

  }
}
#endregion
